spring.application.name=aguagu-hub

# ======================
# PostgreSQL Database
# ======================
spring.datasource.url=${DB_URL:jdbc:postgresql://bkleaf10.asuscomm.com:5777/theorix}
spring.datasource.username=${DB_USERNAME:theorix}
spring.datasource.password=${DB_PASSWORD:xodhflrtm!}
spring.datasource.driver-class-name=org.postgresql.Driver

# ======================
# JPA / Hibernate
# ======================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=aguagu
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# ======================
# Server
# ======================
server.port=8080

# ======================
# Telegram Bot
# ======================
telegram.bot-token=${TELEGRAM_BOT_TOKEN:8325784045:AAE_tcmTCOWmf9BuVRRiuOtKqUClmptKmcU}
telegram.chat-id=${TELEGRAM_CHAT_ID:-5223049219}
telegram.enabled=${TELEGRAM_ENABLED:true}
spring.profiles.active=dev

logging.level.org.apache.coyote.http11.Http11Processor=WARN  

---
spring.config.activate.on-profile=dev